version: 2

build:
  os: ubuntu-24.04

  tools:
    nodejs: "22"

  jobs:
    install:
      - npm ci

    build:
      html:
        - npm run build
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -r dist/* $READTHEDOCS_OUTPUT/html/
